### ISSUE TITLE
Paginated results

### ISSUE THREAD

**Issue by jzisser9** [benoror/ember-airtable#4]
Hi there,
I ran into an issue using this addon. The table I am pulling data from is more than 100 entries long, Airtable's default value to paginate at, so I'm unable to get all of the data in the table.

Does ember-airtable include any way to deal with pagination?

**Comment by benoror** [comment]
Hi @Argus9!

You can pass arbitrary query params to any airtable request, including `pageSize`, for example:

```javascript
      positions: this.store.query('positions', {
        pageSize: 10,
        view: 'myView',
        sort: [{field: "salary", direction: "desc"}],
        filterByFormula: '{name} = "fred"'
      })
```

For more information take a look at  your Airtable base API documentation:

<img width="558" alt="screen shot 2017-06-14 at 13 23 25" src="https://user-images.githubusercontent.com/119117/27148117-b89ef560-5104-11e7-9bbb-f1eb84c6e980.png">


I will close this issue, feel free to re-open if needed. 😄

**Comment by jzisser9** [comment]
Thanks for the info, Ben. My team and I are trying to get around Airtable's pagination entirely and just fetch all of the records in a given table. Is there anything built into `ember-airtable` that can help with that?

**Comment by benoror** [comment]
@Argus9 I don't think so, they limit the api requests for a reason, it's even in [their pricing page](https://airtable.com/pricing), but you can always ask directly to support
